{
 "title": "Main Log",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Login logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"express_api\"} |= \"/api/auth/login\" | json | req_url=\"/api/auth/login\""
    }
   ]
  },
  {
   "title": "Login Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"express_api\"} | json | req_url=\"/api/auth/login\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"express_api\"} | json [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "INFO 2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"express_api\"} | json | level=\"INFO\" [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "WARN 1xx & 3xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"express_api\"} | json | level=\"WARN\" [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "ERROR 4xx & 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"express_api\"} | json | level=\"ERROR\" [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "System Health Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (res_statusCode) (\r\n  count_over_time({job=\"express_api\"} | json [$__range])\r\n)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "System Health Overview",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\r\n  count_over_time({job=\"express_api\"} | json [$__range])\r\n)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "3xx Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"express_api\"} | json | res_statusCode >= 300 | res_statusCode < 400",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "5xx Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"express_api\"} | json | res_statusCode >= 500 | res_statusCode < 600",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "4xx Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"express_api\"} | json | res_statusCode >= 400 | res_statusCode < 500",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Timeout Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"express_api\"} | json | res_statusCode = \"\"",
     "maxLines": 100
    }
   ]
  }
 ]
}